
@url = http://localhost:8090/api


### Get Users ###
######################################################

GET {{url}}/users

###

### Get Posts ###
######################################################

GET {{url}}/posts

###

### Get Posts by Id ###
######################################################

GET {{url}}/posts/1

###

### Create Author ###
######################################################

POST {{url}}/users
Content-Type: application/json

{
  "username": "James",
  "profilePictureUrl": "https://image.png"
},

###

### Create Post ###
######################################################

POST {{url}}/posts
Content-Type: application/json

{
    "author": {
      "id": 1,
      "username": "James",
      "profilePictureUrl": "https://image.png"
    },
    "content": "First post content",
    "timestamp": "2024-04-12T22:07:19.750192",
    "likes": [],
    "comments": [],
    "scores": [],
    "shares": 0,
    "media": [],
    "tags": [],
    "location": null,
    "privacy": null,
    "url": null
  },

###

### Update Post ###
######################################################

PUT {{url}}/posts/1
Content-Type: application/json

{
    "author": {
      " id": 1,
      "username": "James",
      "profilePictureUrl": "https://image.png"
    },
    "content": "First post content updated",
    "timestamp": "2024-04-12T22:07:19.750192",
    "likes": [],
     "comments": [],
    "scores": [],
    "shares": 0,
    "media": [],
    "tags": [],
    "location": null,
    "privacy": null,
    "url": null
  },

###

### Delete Post ###
######################################################

DELETE {{url}}/posts/1

###

### Add Score to Post ###
######################################################

POST {{url}}/posts/1/scores
Content-Type: application/json

{
  "timestamp": "2024-04-12T22:07:19.750192",
  "author": {
    "id": 1,
    "username": "James",
    "profilePictureUrl": "https://avatarfiles.alphacoders.com/793/79317.png"
  },
  "value": 9.5
}

###

### Get Average Score from Post ###
######################################################

GET {{url}}/posts/1/scores/avg

###

### Not Found ###
######################################################

GET {{url}}/not/found